from tkinter import *

root = Tk()
root.geometry("435x390")
root.title("Academy Admission Form")
root.configure(background="aqua")
root.wm_iconbitmap("icon3.ico")

f1 = Frame(root, bg="grey", borderwidth=6, relief=GROOVE, padx=15, pady=20)
f1.pack(ipady=70,ipadx=30)

main_lable = Label(f1, text="Academy Form", font="helvetica 20 bold underline", pady=4, padx=25, fg="white",
      bg="black", relief=SUNKEN).grid(column=1,sticky = "snew")

full_name = Label(f1, text="Full Name: ",bg="grey",font="lucida 12 bold").grid(row=8,column=0,sticky = "snew")
dob = Label(f1, text="DOB: ",bg="grey",font="lucida 12 bold").grid(row=9,sticky = "snew")
age = Label(f1, text="Age: ",bg="grey",font="lucida 12 bold").grid(row=10,sticky = "snew")
grade = Label(f1, text="Class: ",bg="grey",font="lucida 12 bold").grid(row=11,column=0,sticky = "snew")
section = Label(f1, text="Section: ",bg="grey",font="lucida 12 bold").grid(row=12,column=0,sticky = "snew")
elective_subject = Label(f1, text="Elective\n Subjects:",bg="grey",
                         font="lucida 12 bold").grid(row=13,column=0)
session = Label(f1, text="Session: ",bg="grey",font="lucida 12 bold").grid(row=14,column=0,sticky = "snew")
contact_no = Label(f1, text="Contact No: ",bg="grey",font="lucida 12 bold").grid(row=15,column=0,sticky = "snew")
adress = Label(f1, text="Adress: ",bg="grey",font="lucida 12 bold").grid(row=16,column=0,sticky = "snew")

var = int()

radio = Radiobutton(f1,text="Male",padx=14,variable=var,value="Male",activebackground="gray",bg="gray",font="lucida 12 bold").grid(row=4,column=0,sticky = "snew")
radio = Radiobutton(f1,text="Female",padx=14,variable=var,value="female",activebackground="gray",bg="gray",font="lucida 12 bold").grid(row=4,column=1,sticky = "snew")

full_name = StringVar()
dob = StringVar()
age = StringVar()
grade = StringVar()
section = StringVar()
elective_subject = StringVar()
session = StringVar()
contact_no = StringVar()
adress = StringVar()

full_name_entry = Entry(f1, textvariable=full_name,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
dob_entry = Entry(f1, textvariable=dob,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
age_entry = Entry(f1, textvariable=age,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
grade_entry = Entry(f1, textvariable=grade,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
section_entry = Entry(f1, textvariable=section,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
elective_subject_entry = Entry(f1, textvariable=elective_subject,borderwidth=2,relief=SUNKEN,font="lucida 15 bold")
session_entry = Entry(f1, textvariable=session,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
contact_no_entry = Entry(f1, textvariable=contact_no,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")
adress_entry = Entry(f1, textvariable=adress,borderwidth=2,relief=SUNKEN,font="lucida 10 bold")

full_name_entry.grid(row=8, column=1,sticky = "snew")
dob_entry.grid(row=9, column=1,sticky = "snew")
age_entry.grid(row=10, column=1,sticky = "snew")
grade_entry.grid(row=11, column=1,sticky = "snew")
section_entry.grid(row=12, column=1,sticky = "snew")
elective_subject_entry.grid(row=13, column=1, ipady=10,sticky = "snew")
session_entry.grid(row=14, column=1,sticky = "snew")
contact_no_entry.grid(row=15, column=1,sticky = "snew")
adress_entry.grid(row=16, column=1,sticky = "snew")

root.rowconfigure(0,weight=1)
root.rowconfigure(1,weight=1)
root.rowconfigure(2,weight=1)
root.rowconfigure(3,weight=1)
root.rowconfigure(4,weight=1)
root.rowconfigure(5,weight=1)
root.rowconfigure(6,weight=1)
root.rowconfigure(7,weight=1)
root.rowconfigure(8,weight=1)
root.rowconfigure(9,weight=1)
root.rowconfigure(10,weight=1)
root.rowconfigure(11,weight=1)
root.rowconfigure(12,weight=1)
root.rowconfigure(13,weight=1)
root.rowconfigure(14,weight=1)
root.rowconfigure(15,weight=1)
root.rowconfigure(16,weight=1)
root.columnconfigure(0,weight=1)
root.columnconfigure(1,weight=1)

def save():
    f = open("form.txt", "a")
    f.write(f"Full Name: {full_name.get()}\n")
    f.write(f"DOB: {dob.get()}\n")
    f.write(f"Age: {age.get()}\n")
    f.write(f"Class: {grade.get()}\n")
    f.write(f"Section: {section.get()}\n")    
    f.write(f"Elective Subject: {elective_subject.get()}\n")
    f.write(f"Session: {session.get()}\n")
    f.write(f"Contact No: {contact_no.get()}\n")
    f.write(f"Adress: {adress.get()}\n\n")
    f.close()
    root.destroy()

Button(f1, text="Submit", command=save,font="lucida 13 bold",pady=3,relief=RAISED,borderwidth=3).grid(column=1)

root.mainloop()